const en = {
  meta: { langLabel: 'العربية', dir: 'ltr' },
  nav: { about:'About', education:'Education', experience:'Experience', journey:'Journey', projects:'Projects', skills:'Skills', contact:'Contact' },
  hero: { eyebrow:'Available for new opportunities', name:'Salma Ahmed', role:'Software Engineer · Backend Developer', tagline:'From a blank repo to a production-ready product — I design the architecture, build the backend, connect the pieces, and make it ready to scale.', ctaPrimary:'View projects', ctaSecondary:'Get in touch' },
  about: { eyebrow:'About', heading:"I build the parts of a SaaS product that aren't allowed to fail.", paragraphs:["Two years in, I've owned systems most engineers only touch pieces of — tenant isolation, subscription billing, payment webhooks, role-based access. I like the parts of backend work where a mistake is expensive: money, auth, data integrity.","A project I'm especially proud of is Ordex, a multi-tenant commerce platform I built mostly on my own. I worked on everything from the database and backend architecture to the frontend, admin panel, payments, and deployment. It taught me that good architecture isn't just about choosing the right technology — it's about thinking ahead about what can go wrong.","Outside product work, I'm currently deepening my ML fundamentals through an AWS-sponsored AI & ML Scholars program."] },
  education: { eyebrow:'Education', heading:'The foundation behind the builder', items:[{type:'B.Sc.',degree:'Computer Science / Artificial Intelligence',institution:'Faculty of Computers and Artificial Intelligence, Matrouh University',period:'2020 — 2024',grade:'Very Good · GPA 3.3',details:'Graduated in 2024. My graduation project, an Object Following Car built with ESP32-CAM and Arduino, received an A+.',highlights:['A+ Graduation Project','GPA 3.3','ECPC 2021']}] },
  experience: { eyebrow:'Experience', heading:'Where the systems got real', items:[
    {company:'Share Adawli',role:'Software Developer',period:'Feb 2026 — Aug 2026',location:'Jeddah, Saudi Arabia · Remote',points:['Architected the backend for Zumra using NestJS.','Resolved critical HyperPay payment security and webhook issues.','Kept mission-critical services stable in production.']},
    {company:'Runsoft',role:'Backend Developer',period:'Feb 2025 — Dec 2025',location:'Cairo, Egypt',points:['Built and maintained the Laravel/MySQL backend for Bay To Stay.','Designed JWT/OAuth2 authentication flows.','Integrated PayTabs payments and tuned Eloquent queries.']},
    {company:'Orange Digital Center',role:'Software Engineer Trainee',period:'Nov 2024 — Jan 2025',location:'Cairo, Egypt',points:['Built Node.js/Express applications with MongoDB and JWT.','Gained hands-on Agile, SDLC and CI/CD experience.']}
  ]},
  journey: { eyebrow:'Currently diving into', heading:"Still learning, and I don't plan to stop", sections:[
    {label:null,paragraphs:["I used to think learning technology meant reaching a point where you finally know enough.","I don't think that anymore.","Every answer leads to another question, every project opens another door, and I want to understand what is happening underneath everything I build.","That is where I am today."]},
    {label:'The foundation',paragraphs:["I started by building APIs, backends, websites, authentication systems, databases and real products.","The important part was never the list of technologies. It was building something, breaking it, debugging it, asking why, and trying again."]},
    {label:'Learning through failure',paragraphs:["I have also learned through interviews — including the ones I didn't pass.","Every rejection showed me something to improve. Every difficult question became something I wanted to understand instead of simply memorize.","So I kept knocking."]},
    {label:'The AI & ML chapter',paragraphs:["My interest in AI and Machine Learning became more serious through the AWS AI & ML Scholars journey powered by Udacity.","I am continuing self-study in AI and ML, revisiting fundamentals and connecting theory with my engineering experience."]},
    {label:'Still on the road',paragraphs:["My journey has never been a straight line. Projects, bugs, interviews, technologies and opportunities all moved me forward somehow.","Today, I am still building, studying, experimenting and asking: what if I go a little deeper?"]}
  ],closing:"I don't have everything figured out. I just haven't stopped trying.",log:[
    {status:'completed',label:'COMPLETED',text:'AWS AI & ML Scholars — AWS-sponsored learning journey powered by Udacity'},
    {status:'ongoing',label:'ONGOING',text:'AI & ML self-study and coursework'},
    {status:'ongoing',label:'ONGOING',text:'MLOps fundamentals'},
    {status:'exploring',label:'EXPLORING',text:'Deeper AI/ML theory and system design'}
  ]},
  projects: { eyebrow:'Projects', heading:'Selected work', items:[
    {tag:'GET /projects/ordex',title:'Ordex — Commerce OS Platform',description:'A multi-tenant SaaS commerce platform for MENA sellers with isolated storefronts, subscription billing, payments, Redis, BullMQ and Arabic/English RTL support.',stack:['Next.js','Express','TypeScript','PostgreSQL','Prisma','Redis','BullMQ','Docker'],link:'https://ordex.mora-industries.cloud/',linkLabel:'View live',featured:true},
    {tag:'POST /projects/legal-api',title:'Legal Consultation Platform',description:'Backend API for legal appointments, payments, Google Calendar/Meet synchronization and a Gemini-powered legal assistant.',stack:['Node.js','Express','TypeScript','Prisma','PostgreSQL','Google Gemini','Stripe']},
    {tag:'GET /projects/baytostay',title:'Bay To Stay',description:'Rental platform backend with Laravel/MySQL, JWT/OAuth2, Pusher, Firebase and PayTabs.',stack:['Laravel','MySQL','Pusher','Firebase','PayTabs','JWT'],link:'https://play.google.com/store/apps/details?id=com.runsoft.bay_to_stay',linkLabel:'Google Play'},
    {tag:'GET /projects/alinea',title:'ALINEA — AI Behavioral Coach',description:'AI-powered cognitive coaching platform using behavioral signals and Claude AI coaching.',stack:['TypeScript','Next.js','Claude AI','Behavioral Analysis'],link:'https://alinea-sccn.vercel.app/',linkLabel:'View live',link2:'https://github.com/salmahmed6/ALINEA',link2Label:'GitHub'},
    {tag:'GET /projects/ai-recruiter',title:'AI Recruiter Pipeline',description:'Automated n8n pipeline using Gemini to evaluate opportunities and structure an outreach funnel.',stack:['n8n','Google Gemini','Automation','Web Scraping'],link:'https://github.com/salmahmed6/AI-Recruiter-Pipline',linkLabel:'GitHub'},
    {tag:'GET /projects/walk-with-me',title:'Walk With Me',description:'NestJS fitness and mindfulness backend with real-time location, chat, Firebase auth and rewards.',stack:['NestJS','WebSockets','Firebase','MongoDB','TypeScript'],link:'https://github.com/salmahmed6/walk-with-me-mvp',linkLabel:'GitHub'},
    {tag:'npm i node-auth-guard',title:'Node Auth Guard',description:'Reusable JWT authentication, email verification, password reset and RBAC package for Express.',stack:['Node.js','Express','JWT','bcrypt','Joi'],link:'https://github.com/salmahmed6/node-auth-guard',linkLabel:'GitHub'}
  ]},
  skills: { eyebrow:'Skills',heading:'Toolbox',groups:[
    {title:'Languages',items:['JavaScript','TypeScript','Python','PHP','SQL','C++']},{title:'Backend',items:['Node.js','Express.js','NestJS','Laravel','REST APIs','WebSockets','JWT','OAuth2','RBAC']},{title:'Frontend',items:['React','Next.js','Vite','Tailwind CSS','HTML','CSS','React Query','Zustand','Zod']},{title:'Databases & Data',items:['PostgreSQL','MySQL','MongoDB','Redis','BullMQ','Prisma','TypeORM','Eloquent ORM']},{title:'DevOps & Infrastructure',items:['Docker','Git','GitHub Actions','CI/CD','PM2','AWS','Linux','Cloudinary']},{title:'AI / ML / Automation',items:['OpenAI API','Google Gemini','AWS AI & ML','ML fundamentals','MLOps','n8n','Workflow automation']},{title:'Architecture & Practice',items:['Multi-tenancy','SaaS architecture','System design','Payment integrations','Agile','API design','HMAC webhooks']}
  ]},
  contact:{eyebrow:'Contact',heading:"Let's talk",text:'Open to backend and full-stack opportunities.',email:'salmaahmedali924@gmail.com',emailCta:'Send an email',links:[{label:'LinkedIn',href:'https://www.linkedin.com/in/salma-ahmed-988880221/'},{label:'GitHub',href:'https://github.com/salmahmed6'},{label:'X / Twitter',href:'https://x.com/Saloma8_'}]},
  statusBar:{prompt:'status:',status:'available for opportunities',locationLabel:'EGYPT · REMOTE'},
  footer:{text:'Designed & built by Salma Ahmed',backToTop:'Back to top'}
}
export default en